name: Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: echo "dckr_pat_dKDU9NBv5rnNk4B3HBdKoa7L3Tc" | docker login -u "$anzudgaming" --password-stdin docker.io
        docker build --file Dockerfile --tag docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:$GITHUB_SHA
        docker push docker.io/anzudgaming/docker:$GITHUB_SHA
